name: Build and Deploy

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches:
      - "development"
      - "staging"
      - "main"

env:
  IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
  SUBNET_ID: ${{ secrets.SUBNET_ID }}
  REGION: "us-south"
  RESOURCE_GROUP_ID: ${{ secrets.RESOURCE_GROUP_ID }}

jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check variables
        run: |
          echo "IBMCLOUD_API_KEY: $IBMCLOUD_API_KEY"
          echo "SUBNET_ID: $SUBNET_ID"
          echo "REGION: $REGION"
          echo "RESOURCE_GROUP_ID: $RESOURCE_GROUP_ID"
      # - name: Packer Init
      #   run: packer init .

      # - name: Packer Build - Branches
      #   if: "startsWith(github.ref, 'refs/heads/')"
      #   run: packer build . 